import config

class GraphBuilder:

    def __init__(self, links, abstracts):
        # Parsed links dictionary from DBPediaParser
        self.links = links;
        # Parsed abstracts dictionary from DBPediaParser
        self.abstracts = abstracts;
        # how deep do we want to build sub-graph
        self.depth = config.DEPTH;
        # how many nodes are we allowed to fit in graph
        self.max_nodes = config.MAX_NODES
        # where do we save output: path to data/graphs/
        self.output_dir = config.OUTPUT_DIR

    # Public method to build sub-graph surrounding the given seed. It will check if we have a pre-saved graph from this seed first
    def build(self, seed):
        # if cache exists: exit
        # else: call _bfs and save
        print("TODO");

    # Bread-first search from the seed to build out a sub-graph according to the depth & max nodes determined in config file
    def _bfs(self, seed):
        print("TODO");

    # private method to check if a subgraph for given seed has been pre-computed. Check if output_dir/{seed}.json exists
    def _exists(self, seed):
        print("TODO");
        return "TODO";

    # saves the sub-graph generated by bfs to outpur_dir/{seed}.json
    def _save(self, seed, adjacency):
        print("TODO");


