import json
import config
from pathlib import Path
from collections import deque

class GraphBuilder:

    def __init__(self, links, abstracts):
        # Parsed links dictionary from DBPediaParser
        self.links = links;
        # Parsed abstracts dictionary from DBPediaParser
        self.abstracts = abstracts;
        # how deep do we want to build sub-graph
        self.depth = config.DEPTH;
        # how many nodes are we allowed to fit in graph
        self.max_nodes = config.MAX_NODES
        # where do we save output: path to data/graphs/
        self.output_dir = Path(config.OUTPUT_DIR)

    # Public method to build sub-graph surrounding the given seed. It will check if we have a pre-saved graph from this seed first
    def build(self, seed):
        # if cache exists: exit
        # else: call _bfs and save
        if self._exists(seed):
            print(f"Graph for the seed ${seed} has already been cached")
            return
        adjacency = self._bfs(seed)
        self._save(seed, adjacency)

    # Breadth-first search from the seed to build out a sub-graph according to the depth & max nodes determined in config file
    def _bfs(self, seed):
        adjacency = {seed: []}

        queue = deque([(seed, 0)])

        while queue:
            node, current_depth = queue.popleft()
            neighbors = self.links.get(node, [])

            for neighbor in neighbors:
                # skip if neighbor not in links
                if neighbor not in self.links:
                    continue

                # record edge if our neighbor is in the subgraph
                if neighbor in adjacency:
                    if neighbor not in adjacency[node]:
                        adjacency[node].append(neighbor)
                    continue

                # check if hit max_nodes
                if len(adjacency) >= self.max_nodes:
                    continue
                # check fi hit max depth
                if current_depth >= self.depth:
                    continue

                # add the neighbor to the subgraph
                adjacency[neighbor] = []
                adjacency[node].append(neighbor)
                queue.append((neighbor, current_depth + 1))

        return adjacency

    # private method to check if a subgraph for given seed has been pre-computed. Check if output_dir/{seed}.json exists
    def _exists(self, seed):
        return (self.output_dir / f"{seed}.json").exists()

    # saves the sub-graph generated by bfs to outpur_dir/{seed}.json
    def _save(self, seed, adjacency):
        self.output_dir.mkdir(parents=True, exist_ok=True)
        output = {
            "seed": seed,
            "nodes": {
                node: {
                    "abstract": self.abstracts.get(node, ""),
                    "links": neighbors
                }
                for node, neighbors in adjacency.items()
            }
        }
        path = self.output_dir / f"{seed}.json"
        with open(path, "w", encoding="utf-8") as f:
            json.dump(output, f)
        print(f"Sub-graph saved: {path} ({len(adjacency):,} nodes in sub-graph)")

